# Generated by Django 2.1.2 on 2018-10-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_web', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classactive',
            old_name='text',
            new_name='atext',
        ),
        migrations.RenameField(
            model_name='classactive',
            old_name='title',
            new_name='atitle',
        ),
        migrations.RenameField(
            model_name='classnews',
            old_name='text',
            new_name='ntext',
        ),
        migrations.RenameField(
            model_name='classnews',
            old_name='title',
            new_name='ntitle',
        ),
        migrations.RenameField(
            model_name='classnote',
            old_name='text',
            new_name='otext',
        ),
        migrations.RenameField(
            model_name='classnote',
            old_name='title',
            new_name='otitle',
        ),
    ]
